# @deprecated
ns_properties:
    properties:
        default_title:
            title: Заголовок страниц по умолчанию
        meta_keywords:
            title: Ключевые слова сайта
        meta_description:
            title: Описание сайта
        counters:
            title: Счетчики посещаемости
        email_feedback:
            title: Email для формы обратной связи

# @deprecated
ns_feedback:
    recipients: [ italianwind@gmail.com ]
    forms:
        callback:
            title: Форма обратного звонка
            class: generic_callback
            subject: Новая заявка на обратный звонок
            ignore_post: true
            email_template: generic_callback

        feedback:
            title: Форма обратной связи
            subject: Новое сообщение обратной связи
            ignore_post: true
            email_template: generic_feedback