parameters:
    ns_core.service.version.class:        'NS\CoreBundle\Service\VersionService'
    ns_core.service.version.file:         'version.txt'
    ns_core.twig.extension.version.class: 'NS\CoreBundle\Twig\Extension\VersionExtension'

services:
    ns_core.service.changelog:
        class: 'NS\CoreBundle\Service\ChangelogService'
        arguments: ['%kernel.root_dir%/../vendor/neosense/core-bundle/NS/CoreBundle/Resources/changelog.yml']

    ns_core.service.version:
        class: %ns_core.service.version.class%
        arguments: [%ns_core.service.version.file%]

    ns_core.twig.extension.cdn:
        class: 'NS\CoreBundle\Twig\Extension\CdnExtension'
        tags: [{ name: twig.extension }]

    ns_core.twig.extension.version:
        class: %ns_core.twig.extension.version.class%
        arguments: [ @ns_core.service.version ]
        tags: [{ name: twig.extension }]
